all:
  vars:
    mac_and_ip_record: "{{ lookup('ansible.builtin.file', (inventory_dir ~ '/secrets/mac_and_ip_addresses.json')) | ansible.builtin.from_json | ansible.builtin.json_query(inventory_hostname) }}"
    ip_address: "{{ mac_and_ip_record.ip }}"
    mac_address: "{{ mac_and_ip_record.mac }}"
    ansible_host: "{{ ip_address }}"
proxmox_nodes:
  hosts:
    enterprise:

debian_based:
  hosts:
    enterprise:
    andromeda:
    debian12_template:
    centaurus:

devices:
  hosts:
    enterprise:
    andromeda:

containers:
  hosts:
    centaurus:

container_templates:
  hosts:
    debian12_template:
